// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: macinfo.proto

package xyz.sx.collectorcore.protobuf;

public final class Macinfo {
  private Macinfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MacPairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.sx.collectorcore.protobuf.MacPair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mac = 1;</code>
     */
    java.lang.String getMac();
    /**
     * <code>string mac = 1;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();

    /**
     * <code>int32 rssi = 2;</code>
     */
    int getRssi();
  }
  /**
   * Protobuf type {@code xyz.sx.collectorcore.protobuf.MacPair}
   */
  public  static final class MacPair extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.sx.collectorcore.protobuf.MacPair)
      MacPairOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MacPair.newBuilder() to construct.
    private MacPair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MacPair() {
      mac_ = "";
      rssi_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MacPair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mac_ = s;
              break;
            }
            case 16: {

              rssi_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.sx.collectorcore.protobuf.Macinfo.MacPair.class, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder.class);
    }

    public static final int MAC_FIELD_NUMBER = 1;
    private volatile java.lang.Object mac_;
    /**
     * <code>string mac = 1;</code>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      }
    }
    /**
     * <code>string mac = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSSI_FIELD_NUMBER = 2;
    private int rssi_;
    /**
     * <code>int32 rssi = 2;</code>
     */
    public int getRssi() {
      return rssi_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mac_);
      }
      if (rssi_ != 0) {
        output.writeInt32(2, rssi_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mac_);
      }
      if (rssi_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rssi_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.sx.collectorcore.protobuf.Macinfo.MacPair)) {
        return super.equals(obj);
      }
      xyz.sx.collectorcore.protobuf.Macinfo.MacPair other = (xyz.sx.collectorcore.protobuf.Macinfo.MacPair) obj;

      boolean result = true;
      result = result && getMac()
          .equals(other.getMac());
      result = result && (getRssi()
          == other.getRssi());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (37 * hash) + RSSI_FIELD_NUMBER;
      hash = (53 * hash) + getRssi();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.sx.collectorcore.protobuf.Macinfo.MacPair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.sx.collectorcore.protobuf.MacPair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.sx.collectorcore.protobuf.MacPair)
        xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.sx.collectorcore.protobuf.Macinfo.MacPair.class, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder.class);
      }

      // Construct using xyz.sx.collectorcore.protobuf.Macinfo.MacPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mac_ = "";

        rssi_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair getDefaultInstanceForType() {
        return xyz.sx.collectorcore.protobuf.Macinfo.MacPair.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair build() {
        xyz.sx.collectorcore.protobuf.Macinfo.MacPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair buildPartial() {
        xyz.sx.collectorcore.protobuf.Macinfo.MacPair result = new xyz.sx.collectorcore.protobuf.Macinfo.MacPair(this);
        result.mac_ = mac_;
        result.rssi_ = rssi_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.sx.collectorcore.protobuf.Macinfo.MacPair) {
          return mergeFrom((xyz.sx.collectorcore.protobuf.Macinfo.MacPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.sx.collectorcore.protobuf.Macinfo.MacPair other) {
        if (other == xyz.sx.collectorcore.protobuf.Macinfo.MacPair.getDefaultInstance()) return this;
        if (!other.getMac().isEmpty()) {
          mac_ = other.mac_;
          onChanged();
        }
        if (other.getRssi() != 0) {
          setRssi(other.getRssi());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.sx.collectorcore.protobuf.Macinfo.MacPair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.sx.collectorcore.protobuf.Macinfo.MacPair) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mac_ = "";
      /**
       * <code>string mac = 1;</code>
       */
      public java.lang.String getMac() {
        java.lang.Object ref = mac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mac = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        java.lang.Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mac = 1;</code>
       */
      public Builder setMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 1;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 1;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mac_ = value;
        onChanged();
        return this;
      }

      private int rssi_ ;
      /**
       * <code>int32 rssi = 2;</code>
       */
      public int getRssi() {
        return rssi_;
      }
      /**
       * <code>int32 rssi = 2;</code>
       */
      public Builder setRssi(int value) {
        
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rssi = 2;</code>
       */
      public Builder clearRssi() {
        
        rssi_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.sx.collectorcore.protobuf.MacPair)
    }

    // @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.MacPair)
    private static final xyz.sx.collectorcore.protobuf.Macinfo.MacPair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.sx.collectorcore.protobuf.Macinfo.MacPair();
    }

    public static xyz.sx.collectorcore.protobuf.Macinfo.MacPair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MacPair>
        PARSER = new com.google.protobuf.AbstractParser<MacPair>() {
      @java.lang.Override
      public MacPair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MacPair(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MacPair> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MacPair> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.sx.collectorcore.protobuf.Macinfo.MacPair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MacScanLineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.sx.collectorcore.protobuf.MacScanLine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair> 
        getDataList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    xyz.sx.collectorcore.protobuf.Macinfo.MacPair getData(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code xyz.sx.collectorcore.protobuf.MacScanLine}
   */
  public  static final class MacScanLine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.sx.collectorcore.protobuf.MacScanLine)
      MacScanLineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MacScanLine.newBuilder() to construct.
    private MacScanLine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MacScanLine() {
      timestamp_ = 0L;
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MacScanLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Macinfo.MacPair>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Macinfo.MacPair.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.class, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair> data_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    public xyz.sx.collectorcore.protobuf.Macinfo.MacPair getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
     */
    public xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine)) {
        return super.equals(obj);
      }
      xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine other = (xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.sx.collectorcore.protobuf.MacScanLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.sx.collectorcore.protobuf.MacScanLine)
        xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.class, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder.class);
      }

      // Construct using xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.sx.collectorcore.protobuf.Macinfo.internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getDefaultInstanceForType() {
        return xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine build() {
        xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine buildPartial() {
        xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine result = new xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.timestamp_ = timestamp_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine) {
          return mergeFrom((xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine other) {
        if (other == xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Macinfo.MacPair>(data_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Macinfo.MacPair, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder> dataBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder setData(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacPair value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder setData(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder addData(xyz.sx.collectorcore.protobuf.Macinfo.MacPair value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder addData(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacPair value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder addData(
          xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder addData(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacPair> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Macinfo.MacPair.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacPair data = 2;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Macinfo.MacPair, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Macinfo.MacPair, xyz.sx.collectorcore.protobuf.Macinfo.MacPair.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacPairOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.sx.collectorcore.protobuf.MacScanLine)
    }

    // @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.MacScanLine)
    private static final xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine();
    }

    public static xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MacScanLine>
        PARSER = new com.google.protobuf.AbstractParser<MacScanLine>() {
      @java.lang.Override
      public MacScanLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MacScanLine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MacScanLine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MacScanLine> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_sx_collectorcore_protobuf_MacPair_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmacinfo.proto\022\035xyz.sx.collectorcore.pr" +
      "otobuf\"$\n\007MacPair\022\013\n\003mac\030\001 \001(\t\022\014\n\004rssi\030\002" +
      " \001(\005\"V\n\013MacScanLine\022\021\n\ttimestamp\030\001 \001(\003\0224" +
      "\n\004data\030\002 \003(\0132&.xyz.sx.collectorcore.prot" +
      "obuf.MacPairb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_sx_collectorcore_protobuf_MacPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_sx_collectorcore_protobuf_MacPair_descriptor,
        new java.lang.String[] { "Mac", "Rssi", });
    internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_sx_collectorcore_protobuf_MacScanLine_descriptor,
        new java.lang.String[] { "Timestamp", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
