// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensorcollection.proto

package xyz.sx.collectorcore.protobuf;

public final class Sensorcollection {
  private Sensorcollection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorCollectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xyz.sx.collectorcore.protobuf.SensorCollection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> 
        getWifiList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getWifi(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    int getWifiCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder> 
        getWifiOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder getWifiOrBuilder(
        int index);

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> 
        getGpsList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData getGps(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    int getGpsCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder> 
        getGpsOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder getGpsOrBuilder(
        int index);

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> 
        getAccList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getAcc(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    int getAccCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getAccOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getAccOrBuilder(
        int index);

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> 
        getGyrList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getGyr(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    int getGyrCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getGyrOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getGyrOrBuilder(
        int index);

    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> 
        getMagList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getMag(int index);
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    int getMagCount();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getMagOrBuilderList();
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getMagOrBuilder(
        int index);

    /**
     * <code>repeated float ori = 6;</code>
     */
    java.util.List<java.lang.Float> getOriList();
    /**
     * <code>repeated float ori = 6;</code>
     */
    int getOriCount();
    /**
     * <code>repeated float ori = 6;</code>
     */
    float getOri(int index);

    /**
     * <code>repeated int64 step = 7;</code>
     */
    java.util.List<java.lang.Long> getStepList();
    /**
     * <code>repeated int64 step = 7;</code>
     */
    int getStepCount();
    /**
     * <code>repeated int64 step = 7;</code>
     */
    long getStep(int index);

    /**
     * <code>int64 timestamp = 8;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code xyz.sx.collectorcore.protobuf.SensorCollection}
   */
  public  static final class SensorCollection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xyz.sx.collectorcore.protobuf.SensorCollection)
      SensorCollectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorCollection.newBuilder() to construct.
    private SensorCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorCollection() {
      wifi_ = java.util.Collections.emptyList();
      gps_ = java.util.Collections.emptyList();
      acc_ = java.util.Collections.emptyList();
      gyr_ = java.util.Collections.emptyList();
      mag_ = java.util.Collections.emptyList();
      ori_ = java.util.Collections.emptyList();
      step_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                wifi_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine>();
                mutable_bitField0_ |= 0x00000001;
              }
              wifi_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                gps_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData>();
                mutable_bitField0_ |= 0x00000002;
              }
              gps_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                acc_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>();
                mutable_bitField0_ |= 0x00000004;
              }
              acc_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                gyr_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>();
                mutable_bitField0_ |= 0x00000008;
              }
              gyr_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                mag_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>();
                mutable_bitField0_ |= 0x00000010;
              }
              mag_.add(
                  input.readMessage(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.parser(), extensionRegistry));
              break;
            }
            case 53: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                ori_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000020;
              }
              ori_.add(input.readFloat());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                ori_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                ori_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                step_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              step_.add(input.readInt64());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                step_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                step_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 64: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          wifi_ = java.util.Collections.unmodifiableList(wifi_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          gps_ = java.util.Collections.unmodifiableList(gps_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          acc_ = java.util.Collections.unmodifiableList(acc_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          gyr_ = java.util.Collections.unmodifiableList(gyr_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          mag_ = java.util.Collections.unmodifiableList(mag_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          ori_ = java.util.Collections.unmodifiableList(ori_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          step_ = java.util.Collections.unmodifiableList(step_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.sx.collectorcore.protobuf.Sensorcollection.internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.sx.collectorcore.protobuf.Sensorcollection.internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.class, xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.Builder.class);
    }

    private int bitField0_;
    public static final int WIFI_FIELD_NUMBER = 1;
    private java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> wifi_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> getWifiList() {
      return wifi_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder> 
        getWifiOrBuilderList() {
      return wifi_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    public int getWifiCount() {
      return wifi_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getWifi(int index) {
      return wifi_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
     */
    public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder getWifiOrBuilder(
        int index) {
      return wifi_.get(index);
    }

    public static final int GPS_FIELD_NUMBER = 2;
    private java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> gps_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> getGpsList() {
      return gps_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder> 
        getGpsOrBuilderList() {
      return gps_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    public int getGpsCount() {
      return gps_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData getGps(int index) {
      return gps_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
     */
    public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder getGpsOrBuilder(
        int index) {
      return gps_.get(index);
    }

    public static final int ACC_FIELD_NUMBER = 3;
    private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> acc_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getAccList() {
      return acc_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getAccOrBuilderList() {
      return acc_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    public int getAccCount() {
      return acc_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getAcc(int index) {
      return acc_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getAccOrBuilder(
        int index) {
      return acc_.get(index);
    }

    public static final int GYR_FIELD_NUMBER = 4;
    private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> gyr_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getGyrList() {
      return gyr_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getGyrOrBuilderList() {
      return gyr_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    public int getGyrCount() {
      return gyr_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getGyr(int index) {
      return gyr_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getGyrOrBuilder(
        int index) {
      return gyr_.get(index);
    }

    public static final int MAG_FIELD_NUMBER = 5;
    private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> mag_;
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getMagList() {
      return mag_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
        getMagOrBuilderList() {
      return mag_;
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    public int getMagCount() {
      return mag_.size();
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getMag(int index) {
      return mag_.get(index);
    }
    /**
     * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
     */
    public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getMagOrBuilder(
        int index) {
      return mag_.get(index);
    }

    public static final int ORI_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Float> ori_;
    /**
     * <code>repeated float ori = 6;</code>
     */
    public java.util.List<java.lang.Float>
        getOriList() {
      return ori_;
    }
    /**
     * <code>repeated float ori = 6;</code>
     */
    public int getOriCount() {
      return ori_.size();
    }
    /**
     * <code>repeated float ori = 6;</code>
     */
    public float getOri(int index) {
      return ori_.get(index);
    }
    private int oriMemoizedSerializedSize = -1;

    public static final int STEP_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Long> step_;
    /**
     * <code>repeated int64 step = 7;</code>
     */
    public java.util.List<java.lang.Long>
        getStepList() {
      return step_;
    }
    /**
     * <code>repeated int64 step = 7;</code>
     */
    public int getStepCount() {
      return step_.size();
    }
    /**
     * <code>repeated int64 step = 7;</code>
     */
    public long getStep(int index) {
      return step_.get(index);
    }
    private int stepMemoizedSerializedSize = -1;

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 8;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < wifi_.size(); i++) {
        output.writeMessage(1, wifi_.get(i));
      }
      for (int i = 0; i < gps_.size(); i++) {
        output.writeMessage(2, gps_.get(i));
      }
      for (int i = 0; i < acc_.size(); i++) {
        output.writeMessage(3, acc_.get(i));
      }
      for (int i = 0; i < gyr_.size(); i++) {
        output.writeMessage(4, gyr_.get(i));
      }
      for (int i = 0; i < mag_.size(); i++) {
        output.writeMessage(5, mag_.get(i));
      }
      if (getOriList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(oriMemoizedSerializedSize);
      }
      for (int i = 0; i < ori_.size(); i++) {
        output.writeFloatNoTag(ori_.get(i));
      }
      if (getStepList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(stepMemoizedSerializedSize);
      }
      for (int i = 0; i < step_.size(); i++) {
        output.writeInt64NoTag(step_.get(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(8, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < wifi_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, wifi_.get(i));
      }
      for (int i = 0; i < gps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, gps_.get(i));
      }
      for (int i = 0; i < acc_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, acc_.get(i));
      }
      for (int i = 0; i < gyr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, gyr_.get(i));
      }
      for (int i = 0; i < mag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, mag_.get(i));
      }
      {
        int dataSize = 0;
        dataSize = 4 * getOriList().size();
        size += dataSize;
        if (!getOriList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        oriMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < step_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(step_.get(i));
        }
        size += dataSize;
        if (!getStepList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        stepMemoizedSerializedSize = dataSize;
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection)) {
        return super.equals(obj);
      }
      xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection other = (xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection) obj;

      boolean result = true;
      result = result && getWifiList()
          .equals(other.getWifiList());
      result = result && getGpsList()
          .equals(other.getGpsList());
      result = result && getAccList()
          .equals(other.getAccList());
      result = result && getGyrList()
          .equals(other.getGyrList());
      result = result && getMagList()
          .equals(other.getMagList());
      result = result && getOriList()
          .equals(other.getOriList());
      result = result && getStepList()
          .equals(other.getStepList());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWifiCount() > 0) {
        hash = (37 * hash) + WIFI_FIELD_NUMBER;
        hash = (53 * hash) + getWifiList().hashCode();
      }
      if (getGpsCount() > 0) {
        hash = (37 * hash) + GPS_FIELD_NUMBER;
        hash = (53 * hash) + getGpsList().hashCode();
      }
      if (getAccCount() > 0) {
        hash = (37 * hash) + ACC_FIELD_NUMBER;
        hash = (53 * hash) + getAccList().hashCode();
      }
      if (getGyrCount() > 0) {
        hash = (37 * hash) + GYR_FIELD_NUMBER;
        hash = (53 * hash) + getGyrList().hashCode();
      }
      if (getMagCount() > 0) {
        hash = (37 * hash) + MAG_FIELD_NUMBER;
        hash = (53 * hash) + getMagList().hashCode();
      }
      if (getOriCount() > 0) {
        hash = (37 * hash) + ORI_FIELD_NUMBER;
        hash = (53 * hash) + getOriList().hashCode();
      }
      if (getStepCount() > 0) {
        hash = (37 * hash) + STEP_FIELD_NUMBER;
        hash = (53 * hash) + getStepList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xyz.sx.collectorcore.protobuf.SensorCollection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xyz.sx.collectorcore.protobuf.SensorCollection)
        xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return xyz.sx.collectorcore.protobuf.Sensorcollection.internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return xyz.sx.collectorcore.protobuf.Sensorcollection.internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.class, xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.Builder.class);
      }

      // Construct using xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWifiFieldBuilder();
          getGpsFieldBuilder();
          getAccFieldBuilder();
          getGyrFieldBuilder();
          getMagFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (wifiBuilder_ == null) {
          wifi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          wifiBuilder_.clear();
        }
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          gpsBuilder_.clear();
        }
        if (accBuilder_ == null) {
          acc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          accBuilder_.clear();
        }
        if (gyrBuilder_ == null) {
          gyr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          gyrBuilder_.clear();
        }
        if (magBuilder_ == null) {
          mag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          magBuilder_.clear();
        }
        ori_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        step_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return xyz.sx.collectorcore.protobuf.Sensorcollection.internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection getDefaultInstanceForType() {
        return xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.getDefaultInstance();
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection build() {
        xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection buildPartial() {
        xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection result = new xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (wifiBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            wifi_ = java.util.Collections.unmodifiableList(wifi_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.wifi_ = wifi_;
        } else {
          result.wifi_ = wifiBuilder_.build();
        }
        if (gpsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            gps_ = java.util.Collections.unmodifiableList(gps_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.gps_ = gps_;
        } else {
          result.gps_ = gpsBuilder_.build();
        }
        if (accBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            acc_ = java.util.Collections.unmodifiableList(acc_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.acc_ = acc_;
        } else {
          result.acc_ = accBuilder_.build();
        }
        if (gyrBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            gyr_ = java.util.Collections.unmodifiableList(gyr_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.gyr_ = gyr_;
        } else {
          result.gyr_ = gyrBuilder_.build();
        }
        if (magBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            mag_ = java.util.Collections.unmodifiableList(mag_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.mag_ = mag_;
        } else {
          result.mag_ = magBuilder_.build();
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          ori_ = java.util.Collections.unmodifiableList(ori_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.ori_ = ori_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          step_ = java.util.Collections.unmodifiableList(step_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.step_ = step_;
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection) {
          return mergeFrom((xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection other) {
        if (other == xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection.getDefaultInstance()) return this;
        if (wifiBuilder_ == null) {
          if (!other.wifi_.isEmpty()) {
            if (wifi_.isEmpty()) {
              wifi_ = other.wifi_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWifiIsMutable();
              wifi_.addAll(other.wifi_);
            }
            onChanged();
          }
        } else {
          if (!other.wifi_.isEmpty()) {
            if (wifiBuilder_.isEmpty()) {
              wifiBuilder_.dispose();
              wifiBuilder_ = null;
              wifi_ = other.wifi_;
              bitField0_ = (bitField0_ & ~0x00000001);
              wifiBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWifiFieldBuilder() : null;
            } else {
              wifiBuilder_.addAllMessages(other.wifi_);
            }
          }
        }
        if (gpsBuilder_ == null) {
          if (!other.gps_.isEmpty()) {
            if (gps_.isEmpty()) {
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGpsIsMutable();
              gps_.addAll(other.gps_);
            }
            onChanged();
          }
        } else {
          if (!other.gps_.isEmpty()) {
            if (gpsBuilder_.isEmpty()) {
              gpsBuilder_.dispose();
              gpsBuilder_ = null;
              gps_ = other.gps_;
              bitField0_ = (bitField0_ & ~0x00000002);
              gpsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpsFieldBuilder() : null;
            } else {
              gpsBuilder_.addAllMessages(other.gps_);
            }
          }
        }
        if (accBuilder_ == null) {
          if (!other.acc_.isEmpty()) {
            if (acc_.isEmpty()) {
              acc_ = other.acc_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAccIsMutable();
              acc_.addAll(other.acc_);
            }
            onChanged();
          }
        } else {
          if (!other.acc_.isEmpty()) {
            if (accBuilder_.isEmpty()) {
              accBuilder_.dispose();
              accBuilder_ = null;
              acc_ = other.acc_;
              bitField0_ = (bitField0_ & ~0x00000004);
              accBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAccFieldBuilder() : null;
            } else {
              accBuilder_.addAllMessages(other.acc_);
            }
          }
        }
        if (gyrBuilder_ == null) {
          if (!other.gyr_.isEmpty()) {
            if (gyr_.isEmpty()) {
              gyr_ = other.gyr_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureGyrIsMutable();
              gyr_.addAll(other.gyr_);
            }
            onChanged();
          }
        } else {
          if (!other.gyr_.isEmpty()) {
            if (gyrBuilder_.isEmpty()) {
              gyrBuilder_.dispose();
              gyrBuilder_ = null;
              gyr_ = other.gyr_;
              bitField0_ = (bitField0_ & ~0x00000008);
              gyrBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGyrFieldBuilder() : null;
            } else {
              gyrBuilder_.addAllMessages(other.gyr_);
            }
          }
        }
        if (magBuilder_ == null) {
          if (!other.mag_.isEmpty()) {
            if (mag_.isEmpty()) {
              mag_ = other.mag_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMagIsMutable();
              mag_.addAll(other.mag_);
            }
            onChanged();
          }
        } else {
          if (!other.mag_.isEmpty()) {
            if (magBuilder_.isEmpty()) {
              magBuilder_.dispose();
              magBuilder_ = null;
              mag_ = other.mag_;
              bitField0_ = (bitField0_ & ~0x00000010);
              magBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMagFieldBuilder() : null;
            } else {
              magBuilder_.addAllMessages(other.mag_);
            }
          }
        }
        if (!other.ori_.isEmpty()) {
          if (ori_.isEmpty()) {
            ori_ = other.ori_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureOriIsMutable();
            ori_.addAll(other.ori_);
          }
          onChanged();
        }
        if (!other.step_.isEmpty()) {
          if (step_.isEmpty()) {
            step_ = other.step_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureStepIsMutable();
            step_.addAll(other.step_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> wifi_ =
        java.util.Collections.emptyList();
      private void ensureWifiIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          wifi_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine>(wifi_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder> wifiBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> getWifiList() {
        if (wifiBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wifi_);
        } else {
          return wifiBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public int getWifiCount() {
        if (wifiBuilder_ == null) {
          return wifi_.size();
        } else {
          return wifiBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine getWifi(int index) {
        if (wifiBuilder_ == null) {
          return wifi_.get(index);
        } else {
          return wifiBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder setWifi(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine value) {
        if (wifiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiIsMutable();
          wifi_.set(index, value);
          onChanged();
        } else {
          wifiBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder setWifi(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder builderForValue) {
        if (wifiBuilder_ == null) {
          ensureWifiIsMutable();
          wifi_.set(index, builderForValue.build());
          onChanged();
        } else {
          wifiBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder addWifi(xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine value) {
        if (wifiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiIsMutable();
          wifi_.add(value);
          onChanged();
        } else {
          wifiBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder addWifi(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine value) {
        if (wifiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiIsMutable();
          wifi_.add(index, value);
          onChanged();
        } else {
          wifiBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder addWifi(
          xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder builderForValue) {
        if (wifiBuilder_ == null) {
          ensureWifiIsMutable();
          wifi_.add(builderForValue.build());
          onChanged();
        } else {
          wifiBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder addWifi(
          int index, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder builderForValue) {
        if (wifiBuilder_ == null) {
          ensureWifiIsMutable();
          wifi_.add(index, builderForValue.build());
          onChanged();
        } else {
          wifiBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder addAllWifi(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine> values) {
        if (wifiBuilder_ == null) {
          ensureWifiIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, wifi_);
          onChanged();
        } else {
          wifiBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder clearWifi() {
        if (wifiBuilder_ == null) {
          wifi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          wifiBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public Builder removeWifi(int index) {
        if (wifiBuilder_ == null) {
          ensureWifiIsMutable();
          wifi_.remove(index);
          onChanged();
        } else {
          wifiBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder getWifiBuilder(
          int index) {
        return getWifiFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder getWifiOrBuilder(
          int index) {
        if (wifiBuilder_ == null) {
          return wifi_.get(index);  } else {
          return wifiBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder> 
           getWifiOrBuilderList() {
        if (wifiBuilder_ != null) {
          return wifiBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wifi_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder addWifiBuilder() {
        return getWifiFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder addWifiBuilder(
          int index) {
        return getWifiFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.MacScanLine wifi = 1;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder> 
           getWifiBuilderList() {
        return getWifiFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder> 
          getWifiFieldBuilder() {
        if (wifiBuilder_ == null) {
          wifiBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLine.Builder, xyz.sx.collectorcore.protobuf.Macinfo.MacScanLineOrBuilder>(
                  wifi_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          wifi_ = null;
        }
        return wifiBuilder_;
      }

      private java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> gps_ =
        java.util.Collections.emptyList();
      private void ensureGpsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          gps_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData>(gps_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder> gpsBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> getGpsList() {
        if (gpsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gps_);
        } else {
          return gpsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public int getGpsCount() {
        if (gpsBuilder_ == null) {
          return gps_.size();
        } else {
          return gpsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData getGps(int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);
        } else {
          return gpsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder setGps(
          int index, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.set(index, value);
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder setGps(
          int index, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder addGps(xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder addGps(
          int index, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpsIsMutable();
          gps_.add(index, value);
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder addGps(
          xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder addGps(
          int index, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder addAllGps(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData> values) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gps_);
          onChanged();
        } else {
          gpsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder clearGps() {
        if (gpsBuilder_ == null) {
          gps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          gpsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public Builder removeGps(int index) {
        if (gpsBuilder_ == null) {
          ensureGpsIsMutable();
          gps_.remove(index);
          onChanged();
        } else {
          gpsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder getGpsBuilder(
          int index) {
        return getGpsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder getGpsOrBuilder(
          int index) {
        if (gpsBuilder_ == null) {
          return gps_.get(index);  } else {
          return gpsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder> 
           getGpsOrBuilderList() {
        if (gpsBuilder_ != null) {
          return gpsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gps_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder addGpsBuilder() {
        return getGpsFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder addGpsBuilder(
          int index) {
        return getGpsFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.GpsData gps = 2;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder> 
           getGpsBuilderList() {
        return getGpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder> 
          getGpsFieldBuilder() {
        if (gpsBuilder_ == null) {
          gpsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsData.Builder, xyz.sx.collectorcore.protobuf.Gpsinfo.GpsDataOrBuilder>(
                  gps_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          gps_ = null;
        }
        return gpsBuilder_;
      }

      private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> acc_ =
        java.util.Collections.emptyList();
      private void ensureAccIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          acc_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>(acc_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> accBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getAccList() {
        if (accBuilder_ == null) {
          return java.util.Collections.unmodifiableList(acc_);
        } else {
          return accBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public int getAccCount() {
        if (accBuilder_ == null) {
          return acc_.size();
        } else {
          return accBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getAcc(int index) {
        if (accBuilder_ == null) {
          return acc_.get(index);
        } else {
          return accBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder setAcc(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (accBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccIsMutable();
          acc_.set(index, value);
          onChanged();
        } else {
          accBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder setAcc(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (accBuilder_ == null) {
          ensureAccIsMutable();
          acc_.set(index, builderForValue.build());
          onChanged();
        } else {
          accBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder addAcc(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (accBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccIsMutable();
          acc_.add(value);
          onChanged();
        } else {
          accBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder addAcc(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (accBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccIsMutable();
          acc_.add(index, value);
          onChanged();
        } else {
          accBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder addAcc(
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (accBuilder_ == null) {
          ensureAccIsMutable();
          acc_.add(builderForValue.build());
          onChanged();
        } else {
          accBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder addAcc(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (accBuilder_ == null) {
          ensureAccIsMutable();
          acc_.add(index, builderForValue.build());
          onChanged();
        } else {
          accBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder addAllAcc(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> values) {
        if (accBuilder_ == null) {
          ensureAccIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, acc_);
          onChanged();
        } else {
          accBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder clearAcc() {
        if (accBuilder_ == null) {
          acc_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          accBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public Builder removeAcc(int index) {
        if (accBuilder_ == null) {
          ensureAccIsMutable();
          acc_.remove(index);
          onChanged();
        } else {
          accBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder getAccBuilder(
          int index) {
        return getAccFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getAccOrBuilder(
          int index) {
        if (accBuilder_ == null) {
          return acc_.get(index);  } else {
          return accBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
           getAccOrBuilderList() {
        if (accBuilder_ != null) {
          return accBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(acc_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addAccBuilder() {
        return getAccFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addAccBuilder(
          int index) {
        return getAccFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 acc = 3;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder> 
           getAccBuilderList() {
        return getAccFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
          getAccFieldBuilder() {
        if (accBuilder_ == null) {
          accBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder>(
                  acc_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          acc_ = null;
        }
        return accBuilder_;
      }

      private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> gyr_ =
        java.util.Collections.emptyList();
      private void ensureGyrIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          gyr_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>(gyr_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> gyrBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getGyrList() {
        if (gyrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gyr_);
        } else {
          return gyrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public int getGyrCount() {
        if (gyrBuilder_ == null) {
          return gyr_.size();
        } else {
          return gyrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getGyr(int index) {
        if (gyrBuilder_ == null) {
          return gyr_.get(index);
        } else {
          return gyrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder setGyr(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (gyrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGyrIsMutable();
          gyr_.set(index, value);
          onChanged();
        } else {
          gyrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder setGyr(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (gyrBuilder_ == null) {
          ensureGyrIsMutable();
          gyr_.set(index, builderForValue.build());
          onChanged();
        } else {
          gyrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder addGyr(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (gyrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGyrIsMutable();
          gyr_.add(value);
          onChanged();
        } else {
          gyrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder addGyr(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (gyrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGyrIsMutable();
          gyr_.add(index, value);
          onChanged();
        } else {
          gyrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder addGyr(
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (gyrBuilder_ == null) {
          ensureGyrIsMutable();
          gyr_.add(builderForValue.build());
          onChanged();
        } else {
          gyrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder addGyr(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (gyrBuilder_ == null) {
          ensureGyrIsMutable();
          gyr_.add(index, builderForValue.build());
          onChanged();
        } else {
          gyrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder addAllGyr(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> values) {
        if (gyrBuilder_ == null) {
          ensureGyrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gyr_);
          onChanged();
        } else {
          gyrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder clearGyr() {
        if (gyrBuilder_ == null) {
          gyr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          gyrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public Builder removeGyr(int index) {
        if (gyrBuilder_ == null) {
          ensureGyrIsMutable();
          gyr_.remove(index);
          onChanged();
        } else {
          gyrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder getGyrBuilder(
          int index) {
        return getGyrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getGyrOrBuilder(
          int index) {
        if (gyrBuilder_ == null) {
          return gyr_.get(index);  } else {
          return gyrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
           getGyrOrBuilderList() {
        if (gyrBuilder_ != null) {
          return gyrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gyr_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addGyrBuilder() {
        return getGyrFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addGyrBuilder(
          int index) {
        return getGyrFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 gyr = 4;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder> 
           getGyrBuilderList() {
        return getGyrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
          getGyrFieldBuilder() {
        if (gyrBuilder_ == null) {
          gyrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder>(
                  gyr_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          gyr_ = null;
        }
        return gyrBuilder_;
      }

      private java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> mag_ =
        java.util.Collections.emptyList();
      private void ensureMagIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          mag_ = new java.util.ArrayList<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3>(mag_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> magBuilder_;

      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> getMagList() {
        if (magBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mag_);
        } else {
          return magBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public int getMagCount() {
        if (magBuilder_ == null) {
          return mag_.size();
        } else {
          return magBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 getMag(int index) {
        if (magBuilder_ == null) {
          return mag_.get(index);
        } else {
          return magBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder setMag(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (magBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMagIsMutable();
          mag_.set(index, value);
          onChanged();
        } else {
          magBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder setMag(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (magBuilder_ == null) {
          ensureMagIsMutable();
          mag_.set(index, builderForValue.build());
          onChanged();
        } else {
          magBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder addMag(xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (magBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMagIsMutable();
          mag_.add(value);
          onChanged();
        } else {
          magBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder addMag(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3 value) {
        if (magBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMagIsMutable();
          mag_.add(index, value);
          onChanged();
        } else {
          magBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder addMag(
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (magBuilder_ == null) {
          ensureMagIsMutable();
          mag_.add(builderForValue.build());
          onChanged();
        } else {
          magBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder addMag(
          int index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder builderForValue) {
        if (magBuilder_ == null) {
          ensureMagIsMutable();
          mag_.add(index, builderForValue.build());
          onChanged();
        } else {
          magBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder addAllMag(
          java.lang.Iterable<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3> values) {
        if (magBuilder_ == null) {
          ensureMagIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mag_);
          onChanged();
        } else {
          magBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder clearMag() {
        if (magBuilder_ == null) {
          mag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          magBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public Builder removeMag(int index) {
        if (magBuilder_ == null) {
          ensureMagIsMutable();
          mag_.remove(index);
          onChanged();
        } else {
          magBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder getMagBuilder(
          int index) {
        return getMagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder getMagOrBuilder(
          int index) {
        if (magBuilder_ == null) {
          return mag_.get(index);  } else {
          return magBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public java.util.List<? extends xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
           getMagOrBuilderList() {
        if (magBuilder_ != null) {
          return magBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mag_);
        }
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addMagBuilder() {
        return getMagFieldBuilder().addBuilder(
            xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder addMagBuilder(
          int index) {
        return getMagFieldBuilder().addBuilder(
            index, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.getDefaultInstance());
      }
      /**
       * <code>repeated .xyz.sx.collectorcore.protobuf.Vector3 mag = 5;</code>
       */
      public java.util.List<xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder> 
           getMagBuilderList() {
        return getMagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder> 
          getMagFieldBuilder() {
        if (magBuilder_ == null) {
          magBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3.Builder, xyz.sx.collectorcore.protobuf.Vector3OuterClass.Vector3OrBuilder>(
                  mag_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          mag_ = null;
        }
        return magBuilder_;
      }

      private java.util.List<java.lang.Float> ori_ = java.util.Collections.emptyList();
      private void ensureOriIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          ori_ = new java.util.ArrayList<java.lang.Float>(ori_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public java.util.List<java.lang.Float>
          getOriList() {
        return java.util.Collections.unmodifiableList(ori_);
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public int getOriCount() {
        return ori_.size();
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public float getOri(int index) {
        return ori_.get(index);
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public Builder setOri(
          int index, float value) {
        ensureOriIsMutable();
        ori_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public Builder addOri(float value) {
        ensureOriIsMutable();
        ori_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public Builder addAllOri(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureOriIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ori_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float ori = 6;</code>
       */
      public Builder clearOri() {
        ori_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> step_ = java.util.Collections.emptyList();
      private void ensureStepIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          step_ = new java.util.ArrayList<java.lang.Long>(step_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public java.util.List<java.lang.Long>
          getStepList() {
        return java.util.Collections.unmodifiableList(step_);
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public int getStepCount() {
        return step_.size();
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public long getStep(int index) {
        return step_.get(index);
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public Builder setStep(
          int index, long value) {
        ensureStepIsMutable();
        step_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public Builder addStep(long value) {
        ensureStepIsMutable();
        step_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public Builder addAllStep(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureStepIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, step_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 step = 7;</code>
       */
      public Builder clearStep() {
        step_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 8;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xyz.sx.collectorcore.protobuf.SensorCollection)
    }

    // @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.SensorCollection)
    private static final xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection();
    }

    public static xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorCollection>
        PARSER = new com.google.protobuf.AbstractParser<SensorCollection>() {
      @java.lang.Override
      public SensorCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorCollection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorCollection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorCollection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public xyz.sx.collectorcore.protobuf.Sensorcollection.SensorCollection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026sensorcollection.proto\022\035xyz.sx.collect" +
      "orcore.protobuf\032\rmacinfo.proto\032\rgpsinfo." +
      "proto\032\rvector3.proto\"\316\002\n\020SensorCollectio" +
      "n\0228\n\004wifi\030\001 \003(\0132*.xyz.sx.collectorcore.p" +
      "rotobuf.MacScanLine\0223\n\003gps\030\002 \003(\0132&.xyz.s" +
      "x.collectorcore.protobuf.GpsData\0223\n\003acc\030" +
      "\003 \003(\0132&.xyz.sx.collectorcore.protobuf.Ve" +
      "ctor3\0223\n\003gyr\030\004 \003(\0132&.xyz.sx.collectorcor" +
      "e.protobuf.Vector3\0223\n\003mag\030\005 \003(\0132&.xyz.sx" +
      ".collectorcore.protobuf.Vector3\022\013\n\003ori\030\006" +
      " \003(\002\022\014\n\004step\030\007 \003(\003\022\021\n\ttimestamp\030\010 \001(\003b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          xyz.sx.collectorcore.protobuf.Macinfo.getDescriptor(),
          xyz.sx.collectorcore.protobuf.Gpsinfo.getDescriptor(),
          xyz.sx.collectorcore.protobuf.Vector3OuterClass.getDescriptor(),
        }, assigner);
    internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_sx_collectorcore_protobuf_SensorCollection_descriptor,
        new java.lang.String[] { "Wifi", "Gps", "Acc", "Gyr", "Mag", "Ori", "Step", "Timestamp", });
    xyz.sx.collectorcore.protobuf.Macinfo.getDescriptor();
    xyz.sx.collectorcore.protobuf.Gpsinfo.getDescriptor();
    xyz.sx.collectorcore.protobuf.Vector3OuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
